version: '3'
services:
  godbtests:
    container_name: godbtests
    build: ./
    networks:
      - go-db-tests-network

  mysql:
    container_name: godbtests-mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gosqltest
    networks:
      - go-db-tests-network

  postgres:
    container_name: godbtests-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gosqltest
    networks:
      - go-db-tests-network
  
  mssql:
    container_name: godbtests-mssql
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Gosqldbr00t!
    networks:
      - go-db-tests-network

  firebird:
    container_name: godbtests-firebird
    image: jacobalberty/firebird
    environment:
      FIREBIRD_USER: root
      FIREBIRD_PASSWORD: root
      FIREBIRD_DATABASE: gosqltest
    networks:
      - go-db-tests-network
#  oracle:
#    container_name: godbtests-oracle
#    image: container-registry.oracle.com/database/standard
#    networks:
#      - go-db-tests-network

networks:
  go-db-tests-network:
    driver: bridge
